### ISSUE TITLE
Will this work with the LISP-Like language for contracts?

### ISSUE THREAD

**Issue by brendanjerwin** [jorisbontje/cll-sim#14]

**Comment by o-jasper** [comment]
Not currently, but it can be done. I havent looked at LLL very much yet, see no reason it wouldnt be 1-1, and s-expressions are fairly easy to parse.

**Comment by o-jasper** [comment]
I should add, supporting ethereum ASM would automatically support anything compiling to ethereum ASM.

**Comment by brendanjerwin** [comment]
Yeah. That certainly seems like the more right way to go. I wonder if the VM is hostable yet.
